// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_large_ships_admiral = "CgkIwIzq5rwaEAIQBg"; // <GPGSID>
        public const string achievement_50k_kills = "CgkIwIzq5rwaEAIQDQ"; // <GPGSID>
        public const string leaderboard_highscore = "CgkIwIzq5rwaEAIQEQ"; // <GPGSID>
        public const string achievement_50_kills = "CgkIwIzq5rwaEAIQDg"; // <GPGSID>
        public const string achievement_small_ships_captain = "CgkIwIzq5rwaEAIQAw"; // <GPGSID>
        public const string achievement_500_kills = "CgkIwIzq5rwaEAIQDw"; // <GPGSID>
        public const string achievement_5k_kills = "CgkIwIzq5rwaEAIQCg"; // <GPGSID>
        public const string achievement_be_a_space_invader = "CgkIwIzq5rwaEAIQAQ"; // <GPGSID>
        public const string achievement_10k_kills = "CgkIwIzq5rwaEAIQCw"; // <GPGSID>
        public const string achievement_1k_kills = "CgkIwIzq5rwaEAIQCQ"; // <GPGSID>
        public const string achievement_25k_kills = "CgkIwIzq5rwaEAIQDA"; // <GPGSID>
        public const string achievement_42 = "CgkIwIzq5rwaEAIQEA"; // <GPGSID>
        public const string achievement_100_kills = "CgkIwIzq5rwaEAIQCA"; // <GPGSID>
        public const string achievement_fleet_commander = "CgkIwIzq5rwaEAIQBw"; // <GPGSID>
        public const string achievement_support_officer = "CgkIwIzq5rwaEAIQBQ"; // <GPGSID>
        public const string achievement_defense_officer = "CgkIwIzq5rwaEAIQBA"; // <GPGSID>

}

